### ISSUE TITLE
validate CLI Tool - External Schema Validation doesn't work with Web Based Schema Resource Manager 

### ISSUE THREAD

**Issue by tmarrs** [usingjsonschema/ujs-book-materials#1]
I tested the example on page 179 - 181 with the Web Based Schema Resource Manager, and it didn't work properly. The invalid JSON document was considered to be valid. Here's how to reproduce the issue:
## Start tinyserver

```
cd ~/bookujs/chapter3/web
node tinyserver.js 8081
```
## Validate with an invalid JSON instance document over HTTP with validate command

`validate postCanadaInvalid.json postCanada_schema.json`

In the above case, validate considered postCanadaInvalid.json to be valid, which is incorrect.
## Validate with an invalid JSON instance document on the file system with validate command

Please note that validation with the File System Based Schema Resource Manager worked properly:
`validate postCanadaValid.json postCanada_schema.json postCanadaCommon_schema.json`

In this case, validate considered postCanadaInvalid.json to be invalid, which is correct. Great.
## Validate with an invalid JSON instance document on the file system with jsonvalidate web app

When I pasted postCanada_schema.json and postCanadaInValid.json into the jsonvalidate web app and pressed the `Validate` button, postCanadaInValid.json was considered invalid (which is correct).
This worked regardless of whether I filled in the Refs area. 
### What Works
- The `validate` command works when going against the file system.
- The `jsonvalidate` web app works.
### What Doesn't Work
- The `validate` command doesn't work when going over HTTP.

**Comment by joemcintyre** [comment]
Thank you for the report. I have identified the issue in the jsonvalidate tool. I am adding some test cases to cover the http cases and will have the full update posted tonight.

**Comment by joemcintyre** [comment]
jsonvalidate is now updated on npm with the correction, you can update the to the new version (0.1.2) to address the issue.

**Comment by tmarrs** [comment]
I just tested with the new version (from npm) and it works properly. Thanks for fixing this so quickly.
